return
{
    enable = true,
    currentWavesColorG = 127,
    noResize = "",
    countsH = 300,
    countsX = 0,
    countsTransparentWindow = false,
    currentWavesColorB = 0,
    spaceSpawns = true,
    countsNoResize = "",
    countsIndividual = false,
    noTitleBar = "",
    currentWavesColor = 4294934272,
    transparentWindow = false,
    countsY = 0,
    countsW = 400,
    configurationWindowEnable = false,
    AlwaysAutoResize = "",
    countsNoMove = "",
    W = 400,
    noMove = "",
    H = 200,
    countsAlwaysAutoResize = "",
    currentWavesColorR = 255,
    X = 0,
    Y = 0,
    anchor = 1,
    countsNoTitleBar = "",
    countsEnable = true,
    countsDebug = false,
    countsAnchor = 1,
}
