return
{
    enable = true,
    noResize = "",
    countsH = 300,
    countsX = 0,
    countsTransparentWindow = false,
    spaceSpawns = true,
    countsIndividual = false,
    noTitleBar = "",
    transparentWindow = false,
    countsY = 0,
    configurationWindowEnable = false,
    AlwaysAutoResize = "",
    countsW = 400,
    W = 400,
    noMove = "",
    H = 300,
    countsAlwaysAutoResize = "",
    countsNoMove = "",
    countsEnable = true,
    X = 0,
    Y = 0,
    anchor = 3,
    countsNoTitleBar = "",
    countsNoResize = "",
    countsDebug = false,
    countsAnchor = 1,
}
